name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: CI (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ci-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: CI checks
        shell: bash
        run: ./scripts/ci.sh